ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5034:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5034:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Creating a new model archive: tiger_4
Initializing seed to 5432
Traceback (most recent call last):
  File "training/train.py", line 532, in <module>
    main()
  File "training/train.py", line 99, in main
    archive = load_archive(args)
  File "training/train.py", line 469, in load_archive
    archive = ModelArchive(readonly=False, **vars(args))
  File "/home/runzhey/SEAMLeSS/utilities/archive.py", line 133, in __init__
    self._create(*args, **kwargs)
  File "/home/runzhey/SEAMLeSS/utilities/archive.py", line 249, in _create
    self.save()
  File "/home/runzhey/SEAMLeSS/utilities/archive.py", line 462, in save
    self._model.module.save(self.paths['weights'])
  File "/home/runzhey/SEAMLeSS/models/tiger_4/architecture.py", line 43, in save
    torch.save(self.state_dict(), f)
OSError: [Errno 122] Disk quota exceeded
